/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XvHqF6eUns9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Archivo } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"
import { Navbar } from "./navbar"
import { Hero } from "./hero"

export function Ecommerce() {
  const products = [
    {
      id: 1,
      image: "https://images.pexels.com/photos/285034/pexels-photo-285034.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Solar Panels",
      description: "Harness the power of the sun and reduce your energy bills with our high-efficiency solar panels.",
      category: "Solar Panels",
    },
    {
      id: 2,
      image: "https://images.pexels.com/photos/159253/pexels-photo-159253.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Battery Storage",
      description: "Store excess solar energy and power your home during outages with our advanced battery storage solutions.",
      category: "Battery Storage",
    },
    {
      id: 3,
      image: "https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Smart Thermostat",
      description: "Optimize your home's temperature and energy usage with our intuitive smart thermostat.",
      category: "Smart Thermostats",
    },
    {
      id: 4,
      image: "https://images.pexels.com/photos/374238/pexels-photo-374238.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Energy-Efficient Fridge",
      description: "Reduce your energy consumption with our top-of-the-line energy-efficient refrigerators.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 5,
      image: "https://images.pexels.com/photos/268941/pexels-photo-268941.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "LED Light Bulbs",
      description: "Upgrade to our long-lasting, energy-saving LED light bulbs and lower your electricity bills.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 6,
      image: "https://images.pexels.com/photos/1151054/pexels-photo-1151054.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Insulation Panels",
      description: "Improve your home's energy efficiency and reduce heating/cooling costs with our high-performance insulation panels.",
      category: "Insulation",
    },
    {
      id: 7,
      image: "https://images.pexels.com/photos/196667/pexels-photo-196667.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Wind Turbines",
      description: "Generate clean energy with our efficient wind turbines designed for both residential and commercial use.",
      category: "Renewable Energy",
    },
    {
      id: 8,
      image: "https://images.pexels.com/photos/159121/water-bubble-water-bubble-160526.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Water Filtration System",
      description: "Ensure clean and safe drinking water with our advanced water filtration systems.",
      category: "Water Filtration",
    },
    {
      id: 9,
      image: "https://images.pexels.com/photos/1255436/pexels-photo-1255436.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Electric Car Charger",
      description: "Charge your electric vehicle quickly and efficiently with our state-of-the-art car chargers.",
      category: "Electric Car Accessories",
    },
    {
      id: 10,
      image: "https://images.pexels.com/photos/1743230/pexels-photo-1743230.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Solar Water Heater",
      description: "Save on energy costs by using our solar water heaters for your home.",
      category: "Solar Water Heating",
    },
    {
      id: 11,
      image: "https://images.pexels.com/photos/2045543/pexels-photo-2045543.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Energy-Efficient Washer",
      description: "Lower your utility bills with our energy-efficient washing machines.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 12,
      image: "https://images.pexels.com/photos/281512/pexels-photo-281512.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Smart Home Hub",
      description: "Control all your smart home devices from one central hub for increased convenience and efficiency.",
      category: "Smart Home Devices",
    },
    {
      id: 13,
      image: "https://images.pexels.com/photos/109897/pexels-photo-109897.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Energy-Efficient Dryer",
      description: "Dry your clothes faster and more efficiently with our energy-efficient dryers.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 14,
      image: "https://images.pexels.com/photos/1231622/pexels-photo-1231622.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Solar-Powered Generator",
      description: "Keep your home powered during outages with our reliable solar-powered generators.",
      category: "Solar Energy",
    },
    {
      id: 15,
      image: "https://images.pexels.com/photos/261498/pexels-photo-261498.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Smart Light Switch",
      description: "Control your home lighting from anywhere with our easy-to-use smart light switches.",
      category: "Smart Home Devices",
    },
    {
      id: 16,
      image: "https://images.pexels.com/photos/1332193/pexels-photo-1332193.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Energy Monitor",
      description: "Track your energy usage in real-time and optimize consumption with our energy monitors.",
      category: "Energy Management",
    },
    {
      id: 17,
      image: "https://images.pexels.com/photos/288739/pexels-photo-288739.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Solar Attic Fan",
      description: "Keep your attic cool and reduce AC costs with our solar-powered attic fans.",
      category: "Solar Energy",
    },
    {
      id: 18,
      image: "https://images.pexels.com/photos/1445410/pexels-photo-1445410.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Electric Bike",
      description: "Commute efficiently and sustainably with our high-performance electric bikes.",
      category: "Electric Vehicles",
    },
    {
      id: 19,
      image: "https://images.pexels.com/photos/159144/smartphone-cellphone-screen-technology-159144.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Smart Power Strip",
      description: "Protect your devices and save energy with our intelligent power strips.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 20,
      image: "https://images.pexels.com/photos/33774/hd-wallpaper-geometric-gold-pattern.jpg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Thermal Curtains",
      description: "Keep your home warm in winter and cool in summer with our thermal insulated curtains.",
      category: "Energy Efficiency",
    },
    {
      id: 21,
      image: "https://images.pexels.com/photos/3861974/pexels-photo-3861974.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Energy-Efficient Oven",
      description: "Cook efficiently and save on energy with our energy-efficient ovens.",
      category: "Energy-Efficient Appliances",
    },
    {
      id: 22,
      image: "https://images.pexels.com/photos/1225438/pexels-photo-1225438.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Smart Door Lock",
      description: "Secure your home with our advanced smart door locks.",
      category: "Smart Home Devices",
    },
    {
      id: 23,
      image: "https://images.pexels.com/photos/1427022/pexels-photo-1427022.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
      title: "Solar Charger",
      description: "Keep your devices charged on the go with our portable solar chargers.",
      category: "Solar Energy",
    }
  ]
  
  const [selectedCategory, setSelectedCategory] = useState("All")
  const filteredProducts =
    selectedCategory === "All" ? products : products.filter((product) => product.category === selectedCategory)
  const testimonials = [
    {
      id: 1,
      name: "John Doe",
      quote:
        "Switching to solar power with these panels has been a game-changer for my home. I've seen a significant reduction in my energy bills.",
    },
    {
      id: 2,
      name: "Jane Smith",
      quote:
        "The battery storage system has provided me with peace of mind during power outages. I highly recommend it!",
    },
    {
      id: 3,
      name: "Michael Johnson",
      quote:
        "The smart thermostat has made it so easy to manage my home's temperature and energy usage. It's a must-have for any eco-conscious homeowner.",
    },
  ]
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="">
        <Navbar />
        <Hero />
        {/* <div className="container text-primary mx-auto mt-16 p-10">
          <div className="grid gap-6 md:grid-cols-2 md:items-center px-10">
            <div>
              <h1
                className="text-4xl font-bold sm:text-4xl md:text-5xl">
                Power Your Home, Sustainably
              </h1>
              <p className="mt-4 text-lg">
                Discover our range of energy-efficient products that help you save money and reduce your carbon
                footprint.
              </p>
              <Button className="mt-6" size="lg">
                Shop Now
              </Button>
            </div>
            <div className="flex justify-end">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Hero Image"
                className="rounded-lg object-cover" />
            </div>
          </div>
        </div> */}
      </header>
      <main className="flex-1 p-5 lg:p-10">
        <section className="py-12 md:py-16">
          <div className="container mx-auto">
            <div className="mb-8 flex items-center justify-between">
              <h2 className="text-3xl font-bold text-[#de772d]">Our Products</h2>
              <div className="md:flex items-center gap-4 hidden">
                <Button
                  className={selectedCategory === "All" ? "bg-[#de772d]" : "border-2 border-primary bg-white text-primary hover:bg-white"}
                  onClick={() => setSelectedCategory("All")}>
                  All
                </Button>
                <Button
                  className={selectedCategory === "Solar Panels" ? "bg-[#de772d]" : "border-2 border-primary bg-white text-primary hover:bg-white"}
                  onClick={() => setSelectedCategory("Solar Panels")}>
                  Solar Panels
                </Button>
                <Button
                  className={selectedCategory === "Battery Storage" ? "bg-[#de772d]" : "border-2 border-primary bg-white text-primary hover:bg-white"}
                  onClick={() => setSelectedCategory("Battery Storage")}>
                  Battery Storage
                </Button>
                <Button
                  className={selectedCategory === "Smart Thermostats" ? "bg-[#de772d]" : "border-2 border-primary bg-white text-primary hover:bg-white"}
                  onClick={() => setSelectedCategory("Smart Thermostats")}>
                  Smart Thermostats
                </Button>
                <Button
                  className={selectedCategory === "Energy-Efficient Appliances" ? "bg-[#de772d]" : "border-2 border-primary bg-white text-primary hover:bg-white"}
                  onClick={() => setSelectedCategory("Energy-Efficient Appliances")}>
                  Energy-Efficient Appliances
                </Button>
              </div>
            </div>
            <div
              className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {filteredProducts.map((product) => (
                <Card key={product.id} className="hover:scale-105 duration-300 hover:shadow-md">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={300}
                    alt={product.title}
                    className="rounded-t-lg object-cover" />
                  <CardContent>
                    <h3 className="text-xl font-bold text-[#de772d] pt-5">{product.title}</h3>
                    <p className="mt-2 text-muted-foreground">{product.description}</p>
                    <Button className="mt-4" size="sm">
                      Buy Now
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16">
          <div className="container mx-auto">
            <h2 className="mb-8 text-3xl font-bold text-[#de772d]">What Our Customers Say</h2>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              {testimonials.map((testimonial) => (
                <Card key={testimonial.id}>
                  <CardContent>
                    <blockquote className="flex flex-col gap-4 pt-5">
                      <p className="text-muted-foreground">"{testimonial.quote}"</p>
                      <cite className="text-sm font-medium">- {testimonial.name}</cite>
                    </blockquote>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#fff8f2] py-6 px-10">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-4">
            <div>
              <h3 className="mb-4 text-lg font-bold text-[#de772d]">Company</h3>
              <nav className="grid gap-2">
                <Link href="#" prefetch={false}>
                  About Us
                </Link>
                <Link href="#" prefetch={false}>
                  Our Mission
                </Link>
                <Link href="#" prefetch={false}>
                  Careers
                </Link>
                <Link href="#" prefetch={false}>
                  Contact
                </Link>
              </nav>
            </div>
            <div>
              <h3 className="mb-4 text-lg font-bold text-[#de772d]">Products</h3>
              <nav className="grid gap-2">
                <Link href="#" prefetch={false}>
                  Solar Panels
                </Link>
                <Link href="#" prefetch={false}>
                  Battery Storage
                </Link>
                <Link href="#" prefetch={false}>
                  Smart Thermostats
                </Link>
                <Link href="#" prefetch={false}>
                  Energy-Efficient Appliances
                </Link>
              </nav>
            </div>
            <div>
              <h3 className="mb-4 text-lg font-bold text-[#de772d]">Resources</h3>
              <nav className="grid gap-2">
                <Link href="#" prefetch={false}>
                  Blog
                </Link>
                <Link href="#" prefetch={false}>
                  FAQs
                </Link>
                <Link href="#" prefetch={false}>
                  Guides
                </Link>
                <Link href="#" prefetch={false}>
                  Sustainability Tips
                </Link>
              </nav>
            </div>
            <div>
              <h3 className="mb-4 text-lg font-bold text-[#de772d]">Legal</h3>
              <nav className="grid gap-2">
                <Link href="#" prefetch={false}>
                  Privacy Policy
                </Link>
                <Link href="#" prefetch={false}>
                  Terms of Service
                </Link>
                <Link href="#" prefetch={false}>
                  Refund Policy
                </Link>
                <Link href="#" prefetch={false}>
                  Shipping Policy
                </Link>
              </nav>
            </div>
          </div>
          <div className="mt-8 text-center text-sm text-muted-foreground">
            &copy; 2024 Acme Inc. All rights reserved.
          </div>
        </div>
      </footer>
    </div>)
  );
}
