/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RLPb74XatM2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Hero() {
  return (
    (<div>
      <section
        className="py-[300px] md:mt-20 w-full bg-[url('/hero-image.jpg')] bg-cover bg-center md:py-32 lg:py-40">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-6 text-center">
            <h1
              className="text-4xl font-bold tracking-tighter text-black sm:text-5xl md:text-6xl lg:text-7xl">
              Discover the Latest Fashion Trends
            </h1>
            <p className="text-lg text-black md:text-xl lg:text-2xl">
              Explore our curated collection of stylish apparel and accessories for every occasion.
            </p>
            <Link
              href="#"
              className="inline-flex bg-[#de772d] h-12 items-center justify-center rounded-md px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#de772d]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Shop Now
            </Link>
          </div>
        </div>
      </section>
      <section className="bg-[#fff8f2] py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-6 text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Exclusive Discounts</h2>
            <p className="text-muted-foreground md:text-lg">
              Don't miss out on our limited-time discounts. Shop now and save big!
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 flex flex-col bg-[#fff] justify-between duration-300 text-left">
                <h3 className="text-xl font-bold mb-2">20% Off Dresses</h3>
                <p className="text-muted-foreground mb-4">Hurry, this offer ends soon!</p>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#de772d] px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#de772d]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Shop Dresses
                </Link>
              </div>
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 flex flex-col bg-[#fff] justify-between duration-300 text-left">
                <h3 className="text-xl font-bold mb-2">30% Off Accessories</h3>
                <p className="text-muted-foreground mb-4">Don't miss this chance to upgrade your style.</p>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#de772d] px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#de772d]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Shop Accessories
                </Link>
              </div>
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 flex flex-col bg-[#fff] justify-between duration-300 text-left">
                <h3 className="text-xl font-bold mb-2">40% Off Shoes</h3>
                <p className="text-muted-foreground mb-4">Step into style with these amazing deals.</p>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#de772d] px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-[#de772d]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Shop Shoes
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-white py-12 md:py-20">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-6 text-center">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Featured Products</h2>
            <p className="text-muted-foreground md:text-lg">
              Discover our latest collection of stylish and high-quality products.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 duration-300 text-left">
                <div
                  className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
                  <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Cover image"
                    width={300}
                    height={400}
                    className="[grid-area:stack] object-cover w-full aspect-[3/4]" />
                  <div
                    className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-6 justify-end flex flex-col gap-2">
                    <h3 className="font-semibold text-lg tracking-tight">Floral Dress</h3>
                    <p className="text-sm">$59.99</p>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 duration-300 text-left">
                <div
                  className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
                  <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Cover image"
                    width={300}
                    height={400}
                    className="[grid-area:stack] object-cover w-full aspect-[3/4]" />
                  <div
                    className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-6 justify-end flex flex-col gap-2">
                    <h3 className="font-semibold text-lg tracking-tight">Leather Jacket</h3>
                    <p className="text-sm">$149.99</p>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-md p-6 border hover:scale-105 duration-300 text-left">
                <div
                  className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
                  <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                    <span className="sr-only">View</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Cover image"
                    width={300}
                    height={400}
                    className="[grid-area:stack] object-cover w-full aspect-[3/4]" />
                  <div
                    className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-6 justify-end flex flex-col gap-2">
                    <h3 className="font-semibold text-lg tracking-tight">Sneakers</h3>
                    <p className="text-sm">$79.99</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>)
  );
}
